# Generated by Django 4.2.1 on 2023-06-02 09:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='imge',
            new_name='iamge',
        ),
    ]
