# Generated by Django 4.2.1 on 2023-06-04 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0002_rename_imge_product_iamge'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='Brand',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
