# Generated by Django 4.2 on 2023-07-19 00:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0003_product_brand'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='iamge',
            new_name='image',
        ),
    ]
